version: '3'

services:
  react-app:
    image: davedoyle/personal_site:latest
    ports:
      - "3000:3000"
    networks:
      - my_network

  nginx-proxy:
    image: davedoyle/nginx-image:tag
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
